"""
MeshConverter: 将 Gmsh 网格数据转换为 FLAC3D 可读格式。

支持两种输出：
  1. .f3grid 文本格式（首选）— FLAC3D zone import 直接读取
  2. .dat 命令格式（备选）— zone create tetrahedron 逐单元创建
"""

import numpy as np


class MeshConverter:
    """Gmsh 网格数据 → FLAC3D 格式转换器。"""

    def __init__(self, node_ids, nodes, element_ids, elements,
                 element_groups, layers_slot='layers'):
        """
        :param node_ids: (N,) 节点编号数组
        :param nodes: (N, 3) 节点坐标数组
        :param element_ids: (M,) 单元编号数组
        :param elements: (M, 4) 四面体连接数组（节点编号）
        :param element_groups: (M,) 分组名称数组
        :param layers_slot: FLAC3D group slot 名称
        """
        self.node_ids = node_ids
        self.nodes = nodes
        self.element_ids = element_ids
        self.elements = elements
        self.element_groups = element_groups
        self.layers_slot = layers_slot

    def write_f3grid(self, output_path):
        """
        写入 FLAC3D .f3grid 文本格式。

        格式规范：
          * FLAC3D grid file
          * GRIDPOINTS
          G <id> <x> <y> <z>
          ...
          * ZONES: Tetrahedra
          Z T4 <id> <gp1> <gp2> <gp3> <gp4>
          ...
          * GROUPS
          ZGROUP "<group_name>" SLOT "<slot_name>"
           <zone_id_1> <zone_id_2> ...

        :param output_path: 输出文件路径
        :return: 写入的文件路径
        """
        n_nodes = len(self.node_ids)
        n_elements = len(self.element_ids)

        print(f"[MeshConverter] Writing .f3grid: {n_nodes} nodes, {n_elements} zones -> {output_path}")

        # 重新编号节点和单元（FLAC3D 使用 1-based 连续编号）
        # 构建 Gmsh node_id -> FLAC3D gp_id 的映射
        node_id_map = {}
        for new_id, old_id in enumerate(self.node_ids, start=1):
            node_id_map[int(old_id)] = new_id

        with open(output_path, 'w', encoding='utf-8') as f:
            # Header
            f.write("* FLAC3D grid file generated by SlopeRA3D (GmshMesher)\n")
            f.write(f"* Nodes: {n_nodes}, Zones: {n_elements}\n")

            # Gridpoints
            f.write("* GRIDPOINTS\n")
            for i, (nid, coord) in enumerate(zip(self.node_ids, self.nodes)):
                gp_id = node_id_map[int(nid)]
                f.write(f"G\t{gp_id}\t{coord[0]:.8g}\t{coord[1]:.8g}\t{coord[2]:.8g}\n")

            # Zones (Tetrahedra)
            f.write("* ZONES: Tetrahedra\n")
            zone_id_map = {}  # old element_id -> new zone_id
            for i, (eid, conn) in enumerate(zip(self.element_ids, self.elements)):
                zone_id = i + 1
                zone_id_map[int(eid)] = zone_id
                # 映射节点编号
                gp1 = node_id_map.get(int(conn[0]), int(conn[0]))
                gp2 = node_id_map.get(int(conn[1]), int(conn[1]))
                gp3 = node_id_map.get(int(conn[2]), int(conn[2]))
                gp4 = node_id_map.get(int(conn[3]), int(conn[3]))
                f.write(f"Z T4\t{zone_id}\t{gp1}\t{gp2}\t{gp3}\t{gp4}\n")

            # Groups
            f.write("* GROUPS\n")

            # 按分组收集 zone IDs
            group_zones = {}
            for i, (eid, grp) in enumerate(zip(self.element_ids, self.element_groups)):
                grp_name = str(grp)
                if grp_name not in group_zones:
                    group_zones[grp_name] = []
                group_zones[grp_name].append(i + 1)  # 1-based zone_id

            for grp_name, zone_ids in group_zones.items():
                f.write(f'ZGROUP "{grp_name}" SLOT "{self.layers_slot}"\n')
                # 每行写 10 个 ID
                for j in range(0, len(zone_ids), 10):
                    batch = zone_ids[j:j+10]
                    f.write("   " + " ".join(str(z) for z in batch) + "\n")

        print(f"  [Success] .f3grid written: {output_path}")
        self._print_stats()
        return output_path

    def write_dat_commands(self, output_path=None):
        """
        生成 FLAC3D .dat 命令格式（备选方案）。

        :param output_path: 若提供则写入文件，否则返回命令列表
        :return: 命令字符串列表
        """
        cmds = [
            "; Auto-generated mesh import commands by SlopeRA3D (GmshMesher)",
            f"; Nodes: {len(self.node_ids)}, Zones: {len(self.element_ids)}",
            "",
            "; --- Gridpoints ---",
        ]

        # 重新编号
        node_id_map = {}
        for new_id, old_id in enumerate(self.node_ids, start=1):
            node_id_map[int(old_id)] = new_id

        for nid, coord in zip(self.node_ids, self.nodes):
            gp_id = node_id_map[int(nid)]
            cmds.append(
                f"zone gridpoint create id {gp_id} "
                f"position ({coord[0]:.8g},{coord[1]:.8g},{coord[2]:.8g})"
            )

        cmds.append("")
        cmds.append("; --- Zones (Tetrahedra) ---")

        for i, (eid, conn) in enumerate(zip(self.element_ids, self.elements)):
            zone_id = i + 1
            gp1 = node_id_map.get(int(conn[0]), int(conn[0]))
            gp2 = node_id_map.get(int(conn[1]), int(conn[1]))
            gp3 = node_id_map.get(int(conn[2]), int(conn[2]))
            gp4 = node_id_map.get(int(conn[3]), int(conn[3]))
            cmds.append(
                f"zone create tetrahedron "
                f"point 0 gridpoint {gp1} "
                f"point 1 gridpoint {gp2} "
                f"point 2 gridpoint {gp3} "
                f"point 3 gridpoint {gp4}"
            )

        # Groups
        cmds.append("")
        cmds.append("; --- Groups ---")
        group_zones = {}
        for i, grp in enumerate(self.element_groups):
            grp_name = str(grp)
            if grp_name not in group_zones:
                group_zones[grp_name] = []
            group_zones[grp_name].append(i + 1)

        for grp_name, zone_ids in group_zones.items():
            # 使用 range id 批量分组
            cmds.append(f"zone group '{grp_name}' slot '{self.layers_slot}' range id {zone_ids[0]} {zone_ids[-1]}")

        if output_path:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(cmds))
            print(f"[MeshConverter] .dat commands written: {output_path}")

        return cmds

    def _print_stats(self):
        """打印网格统计信息。"""
        if self.element_groups is None or len(self.element_groups) == 0:
            return

        unique_groups, counts = np.unique(self.element_groups, return_counts=True)
        print("  Mesh Statistics:")
        print(f"    Total nodes    : {len(self.node_ids)}")
        print(f"    Total zones    : {len(self.element_ids)}")
        print(f"    Groups:")
        for grp, cnt in zip(unique_groups, counts):
            print(f"      {grp:20s}: {cnt:6d} zones")
